version: "3.8"

networks:
  ExposeNet:


services:
  ftpserver:
    image: openjdk:17
    container_name: ftpserver
    ports:
      - "21:21"
    volumes:
      - "./FtpServer.jar:/FtpServer.jar"
    command:
      - /bin/bash
      - -c
      - |
        java -jar /FtpServer.jar


