name: "打包部署FTP服务器"

on: push
permissions:
  contents: write

jobs:
  run-image:
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库的内容
        uses: actions/checkout@v4

      - name: 在Docker中部署并运行FTP服务器
        run: docker compose -f build/docker-compose.yaml -p package up -d

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build


